import { Injectable, Logger } from '@nestjs/common';
import * as QRCode from 'qrcode';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

@Injectable()
export class CertificatesService {
  private readonly logger = new Logger(CertificatesService.name);

  /**
   * Generates a QR Code as a DataURL or Buffer
   */
  async generateQRCode(data: string): Promise<string> {
    try {
      return await QRCode.toDataURL(data);
    } catch (err) {
      this.logger.error('Failed to generate QR Code', err);
      throw err;
    }
  }

  /**
   * Generates a digital birth certificate PDF
   */
  async generateBirthCertificatePdf(record: any): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([600, 400]);
    const { width, height } = page.getSize();
    
    const font = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

    // Title
    page.drawText('RÉPUBLIQUE DE GUINÉE', {
      x: 50,
      y: height - 50,
      size: 20,
      font: font,
      color: rgb(0, 0.5, 0),
    });

    page.drawText('Extrait d\'Acte de Naissance Numérique', {
      x: 50,
      y: height - 80,
      size: 15,
      font: font,
    });

    // Data
    const drawLabelValue = (label: string, value: string, y: number) => {
      page.drawText(`${label}:`, { x: 50, y, size: 12, font: font });
      page.drawText(value || 'N/A', { x: 200, y, size: 12, font: regularFont });
    };

    drawLabelValue('IUN', record.iun, height - 120);
    drawLabelValue('Nom', record.childLastName, height - 140);
    drawLabelValue('Prénoms', record.childFirstName, height - 160);
    drawLabelValue('Date de Naissance', record.childDob.toLocaleDateString(), height - 180);
    drawLabelValue('Lieu', record.childBirthPlace, height - 200);
    drawLabelValue('Mère', record.motherName, height - 220);

    // Blockchain Proof
    page.drawText('PREUVE BLOCKCHAIN', { x: 50, y: 100, size: 10, font: font });
    page.drawText(`Hash: ${record.childHash?.substring(0, 32)}...`, { x: 50, y: 85, size: 8, font: regularFont });
    page.drawText(`TX: ${record.blockchainTx?.substring(0, 32)}...`, { x: 50, y: 70, size: 8, font: regularFont });

    // QR Code placeholder (actual logic would embed the image generated by generateQRCode)
    page.drawText('[Scannez pour vérifier]', { x: 450, y: 50, size: 10, font: regularFont });

    return await pdfDoc.save();
  }
}
